fix(deps): update to cli-table3
horacehylee/workenv-cli pull request #1
Opened 2018-06-20 08:33 UTC by schalkneethling

This PR updates the cli-table2 dependency to cli-table3, which fixes one of the npm audit warnings :)

cli-table2 (like cli-table itself) is no longer maintained. In jamestalmage/cli-table2#43 a couple of people have offered to take over maintenance but the current maintainer did not respond so as a result the project was forked to cli-table/cli-table3.

2018-06-24 04:50 UTC, horacehylee commented
Could you fix the error by changing the `@types/lowdb@^1.0.2` in the yarn.lock file back to `@types/lowdb@^1.0.0`

2018-06-25 07:59 UTC, schalkneethling commented
@horacehylee I guess it upgraded to the latest because the version is not locked down to `1.0.0`, that is an option to ensure this does not happen. So, are you happy if I lock it down? aka `@types/lowdb@1.0.0`

2018-06-25 16:19 UTC, horacehylee commented
@schalkneethling, Sure please lock it down for now, to let the test pass.
I will submit another pull request to update the use of lowdb with the latest type definition.
Thanks for the pull request.

2018-06-25 16:21 UTC, horacehylee requested changes

2018-06-25 16:22 UTC, horacehylee requested changes
Please lock the @types/lowdb to v1.0.0 to let the test pass

2018-06-26 14:16 UTC, horacehylee approved these changes

2018-06-26 14:16 UTC, horacehylee commented
@schalkneethling Thanks.

2018-06-26 14:16 UTC, merged